### ISSUE TITLE
password issue (0.3.7 SUCC but 0.3.8 FAIL)

### ISSUE THREAD

**Issue by sxyizhiren** [mscdex/node-ftp#111]
hi , i have a ftp server(but i don't have its source code), it doesn't need password.
then i met a problem, when i use 0.3.7 ,it is ok. 
when i use 0.3.8 it failed ,and got an error "[Error: Use Login with USER first.]".

debug info:
i add a print here(line 216):

else if (cmd === 'USER') {
console.log('USER code,',code)
/*
if (code === 331) {
...

and it print "USER code, 230"

also here is the call trace.
FTP error { [Error: Use Login with USER first.] code: 503 }
Error: Use Login with USER first.
    at makeError (D:\ftp_home\tmp\qimjin\autoCmdDbg\node_modules\ftp\lib\connection.js:1074:13)
    at Parser.<anonymous> (D:\ftp_home\tmp\qimjin\autoCmdDbg\node_modules\ftp\lib\connection.js:113:25)
    at Parser.emit (events.js:98:17)
    at Parser._write (D:\ftp_home\tmp\qimjin\autoCmdDbg\node_modules\ftp\lib\parser.js:58:10)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Parser.Writable.write (_stream_writable.js:183:11)
    at Socket.ondata (D:\ftp_home\tmp\qimjin\autoCmdDbg\node_modules\ftp\lib\connection.js:284:20)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)

**Comment by mscdex** [comment]
Can you show the client code you are using?

**Comment by sxyizhiren** [comment]
@mscdex 

var config= JSON.parse(fs.readFileSync('xxxx.json')));
/*
{
    "host": "192.168.254.69",
    "port": 21,
    "user": "anonymous",
    "password": "anonymous@"
}
*/

var FTPClient = require('ftp');
var c = new FTPClient();

c.on('error', function (error) {
	//here catch the Error 
});

c.on('close', function (had_error) {
	console.log('close', had_error);
});

c.on('end', function () {
	console.log('end');
});

c.on('greeting', function (text) {
	// here seems reached
	console.log(text);
});

c.on('ready', function() {
	//here means connect succeed, but of course not reach here.
	connectCallback();
});

c.connect(config);

**Comment by mscdex** [comment]
Hrmm.... if you add `debug: console.log` to your `config` object, what does it show?

**Comment by sxyizhiren** [comment]
[connection] < '220 Welcome to OSE FTP server (Version ose5.3).\r\n'
[parser] < '220 Welcome to OSE FTP server (Version ose5.3).\r\n'
[parser] Response: code=220, buffer='Welcome to OSE FTP server (Version ose5.3).
'
Welcome to OSE FTP server (Version ose5.3).
[connection] > 'USER anonymous'
Welcome to OSE Shell ose5.3.

[connection] < '230 User logged in.\r\n'
[parser] < '230 User logged in.\r\n'
[parser] Response: code=230, buffer='User logged in.'
[connection] > 'PASS anonymous@'
$
[connection] < '503 Use Login with USER first.\r\n'
[parser] < '503 Use Login with USER first.\r\n'
[parser] Response: code=503, buffer='Use Login with USER first.'
FTP error { [Error: Use Login with USER first.] code: 503 }
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Use Login with USER first.
    at makeError (D:\rfswcmdNew\node_modules\rfswcmd\node_modules\ftp\lib\connec
tion.js:1071:13)
    at Parser.<anonymous> (D:\rfswcmdNew\node_modules\rfswcmd\node_modules\ftp\l
ib\connection.js:113:25)
    at Parser.emit (events.js:110:17)
    at Parser._write (D:\rfswcmdNew\node_modules\rfswcmd\node_modules\ftp\lib\pa
rser.js:58:10)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (D:\rfswcmdNew\node_modules\rfswcmd\node_modules\ftp\lib\co
nnection.js:281:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

**Comment by mscdex** [comment]
Can you please try the master branch? The problematic commit should be reverted now.

**Comment by sxyizhiren** [comment]
by using the connection.js from master branch(other file all from 0.3.7), it can work.

**Comment by mscdex** [comment]
Thanks for the confirmation. v0.3.9 published to npm.
