### ISSUE TITLE
ECONNRESET Error using ftp

### ISSUE THREAD

**Issue by StuartMorris0** [mscdex/node-ftp#126]
Hello,

I am experiencing an issue on one windows machine trying to use node-ftp. The issue appears to be network related, as I can complete this on another machine without issue.

The script I am using is the following:
`   
var FTP = require( 'ftp' );
var client = new FTP();

client.on( 'ready', onReady );

function onReady() {
	client.list( '/', onList );
}

function onList( err, list ) {
	if ( err ) console.log( err.stack );
	else console.log( list );
}

client.connect( {
	user: '',
	password: '',
	host: '',
	debug: console.log.bind( console )
} );
`

The error is shown here:
![nodeftperror](https://cloud.githubusercontent.com/assets/1994135/9331942/07da6fa4-45ba-11e5-9f98-25aeee99a4c5.png)

FileZilla on the same machine with the same setup seems to work without issue.

Is there anything that could be causing this?

Thanks

**Comment by PinkPandaAU** [comment]
+1 for this, getting the same error

**Comment by igabesz** [comment]
+1, got similar issues from a Linux server. Our Node.js script is launched daily with cron, and I often got the same ECONNRESET error.

**Comment by SubZane** [comment]
+1 as I get the same error using any gulp, grunt plugins using the node-ftp module

**Comment by leggomuhgreggo** [comment]
+1

**Comment by ruiwei** [comment]
Seems this happening when node code behind certain firewall, such as dell's sonicwall. Set socket keep alive to false should fix this problem. 

connection.js line 106
`socket.setKeepAlive(false);`

Add an option would be nice.

**Comment by michalhudecek** [comment]
+1 same error, it make the library unusable

**Comment by CcHard** [comment]
+1

**Comment by radiocold** [comment]
+1 same error

**Comment by lajlev** [comment]
+1 same error

Only on specific networks. I was only able to solve it by using with my private VPN 😔

**Comment by bllevy** [comment]
I get this same error when downloading a large file via FTP.

**Comment by gabrielCortesReyes** [comment]
+1, same error, but sometimes it works

`read ECONNRESET
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

**Comment by matheusrolima** [comment]
I was having the same problem, but after this command every all its okay now : 

npm install @ionic/app-scripts@nightly --save-dev

**Comment by giuvincenzi** [comment]
The fix is ​​on master branch but it is not in a new version of npm. 
The latest version of npm is `0.3.10` and does not have the fix that is on master branch.

Please update,
Thank you.

**Comment by sagardere** [comment]
I have a problem when I connect localhost using FTP server. Give me suggestions

> err { Error: connect ECONNREFUSED 127.0.0.1:21
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 21 }

I am also changing port but it not work.

**Comment by vestige06** [comment]
You have to put pass "pasv_url" value to its constructor :
 
const ftpServer = new FtpSrv({
  url:'ftp://' + '127.0.0.1' + ':' + '21', 
  pasv_url:'0.0.0.0', 
  anonymous: true
 });
it's work for me .

**Comment by Robguzi** [comment]
My application connects to a filezilla server to perform a put method.  The file appears on the server without issue, but I always see this error: read ECONNRESET.  The server and my client application are on the same LAN.  The keepalive false suggestion has no effect for me.
