### ISSUE TITLE
Too many parallel connection error

### ISSUE THREAD

**Issue by kenichi-shibata** [mscdex/node-ftp#138]
```
{"message":"There are too many connections from your internet address.","name":"Error","stack":"Error: There are too many connections from your internet address.\n    at makeError (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/ftp/lib/connection.js:1067:13)\n    at Parser.<anonymous> (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/ftp/lib/connection.js:113:25)\n    at emitTwo (events.js:87:13)\n    at Parser.emit (events.js:172:7)\n    at Parser._write (/Users/00831103/Workspace/project-2/image-pf-node/node_modules/ftp/lib/parser.js:59:10)\n    at doWrite (_stream_writable.js:292:12)\n    at writeOrBuffer (_stream_writable.js:278:5)\n    at Parser.Writable.write (_stream_writable.js:207:11)\n    at Socket.ondata (/Users/00831103/Workspace/project-2/-pf-node/node_modules/ftp/lib/connection.js:273:20)\n    at emitOne (events.js:77:13)","code":421},"msg":"There are too many connections from your internet address.
```

**Comment by mscdex** [comment]
There's nothing this module can do about that. It does not open multiple connections by itself. You will either need to lower the number of simultaneous connections or have some sort of retry algorithm if your IP is shared with others.
