### ISSUE TITLE
Error: Timed out while making data connection

### ISSUE THREAD

**Issue by hooper-hc** [mscdex/node-ftp#163]
I used the terminal command in FTP to connect to the FTP server, I can normally get/put,
![qq20161127-0 2x](https://cloud.githubusercontent.com/assets/11420374/20647326/70526dfc-b4cc-11e6-80d9-a6d6bb59ad04.png)

but after using the node-ftp connection to the server using the put error.
Code:
```javascript
client.put(`${outputPath}/${sourceZip}`, '/Gzip.tar.gz', (err) => {
    if (err) {
        phisay.fail(err);
        console.log(err);
        // reject(err);
    }
    client.end();
});
```
Error code:
[MSG] [connection] > 'PASV'
[MSG] [connection] < '227 Entering Passive Mode (...).\r\n'
[MSG] [parser] < '227 Entering Passive Mode (...).\r\n'
[MSG] [parser] Response: code=227, buffer='Entering Passive Mode (...).'
[MSG] [connection] > 'ABOR'
[MSG] [connection] < '226 Abort successful\r\n'
[MSG] [parser] < '226 Abort successful\r\n'
[MSG] [parser] Response: code=226, buffer='Abort successful'
[FAIL] Error: Timed out while making data connection
Error: Timed out while making data connection
    at Timeout.<anonymous> (/Users/..../git/shell/node_modules/ftp/lib/connection.js:901:12)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by hooper-hc** [comment]
node-fep version: "ftp": "^0.3.10",
