### ISSUE TITLE
ECONNREFUSED using ftp

### ISSUE THREAD

**Issue by zamanex** [mscdex/node-ftp#174]
Same Error for default and using credentials.  
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:3500
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by Stumblor** [comment]
I get this too - when connecting for the second time (during a setInterval loop).

**Comment by firminochangani** [comment]
I am getting the same error.

**Comment by Slyteer** [comment]
Yea guys i have the same one ;) #wheresolikeeatchother
But do you have a solution ?

**Comment by yasyash** [comment]
Hello,
I have the same error when the FTP server is down, but how can I handle this error?
Thanks!

**Comment by yasyash** [comment]
I've resolved this issue like that.
Cause of error: no connection to the server.
This problem pops up in the conn.connect() function.
If I made the following construction: 
                                                    try {
                                                            conn.connect(options, { debug: debug });
                                                        }
                                                        catch (err) {
                                                            console.log('FTP connection error catched:  ', err);
                                                        }

The app didn't crash, displaying an error in the console.

**Comment by vitoresende** [comment]
I am getting the same error. I've tried what @yasyash commented but it didn't work for me.

**Comment by anujpachawadkar** [comment]
Even I am getting the same error and that too for localhost, Please provide solution for this if anyone has got!

**Comment by anujpachawadkar** [comment]
> I've resolved this issue like that.
> Cause of error: no connection to the server.
> This problem pops up in the conn.connect() function.
> If I made the following construction:
> try {
> conn.connect(options, { debug: debug });
> }
> catch (err) {
> console.log('FTP connection error catched: ', err);
> }
> 
> The app didn't crash, displaying an error in the console.

But that doesn't give you any solution to the problem.
