### ISSUE TITLE
Multiple asynchronous calls to put() breaks with ECONNRESET

### ISSUE THREAD

**Issue by samuelt1** [mscdex/node-ftp#211]
Running multiple asynchronous calls to the put function will break things. the returned error is:
```{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
  cause: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  isOperational: true,
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read' }
```
A simple test for this is:
```
let promises = []
for(let i = 0;i>100;i++)
promises.push(ftp.put('a file','a/folder/name'+i))

await Promise.All(promises)

**Comment by x-guang** [comment]
The problem might be due to the limit that FTP can execute only a task at the same time.

**Comment by edthenet** [comment]
+1
