### ISSUE TITLE
Error: OOPS: vsf_sysutil_recv_peek: no data

### ISSUE THREAD

**Issue by hydrotik** [mscdex/node-ftp#50]
Getting this error using the simple FTP put command:

Error: OOPS: vsf_sysutil_recv_peek: no data
    at makeError (/Volumes/Data/Node/ddoservices/node_modules/ftp/lib/ftp.js:1089:13)
    at Socket.ondata (/Volumes/Data/Node/ddoservices/node_modules/ftp/lib/ftp.js:271:30)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:525:21)

**Comment by atasciuc** [comment]
Got same error here:
```
 'Error: OOPS: vsf_sysutil_recv_peek: no data',
     '    at makeError (/Users/flexalex/Desktop/Code/FTPListener/FTPPULL/node_modules/ftp/lib/connection.js:1067:13)',
     '    at Parser.<anonymous> (/Users/flexalex/Desktop/Code/FTPListener/FTPPULL/node_modules/ftp/lib/connection.js:115:28)',
     '    at Parser.emit (events.js:110:17)',
     '    at Parser._write (/Users/flexalex/Desktop/Code/FTPListener/FTPPULL/node_modules/ftp/lib/parser.js:59:10)',
     '    at doWrite (_stream_writable.js:301:12)',
     '    at writeOrBuffer (_stream_writable.js:288:5)',
     '    at Parser.Writable.write (_stream_writable.js:217:11)',
     '    at Socket.ondata (/Users/flexalex/Desktop/Code/FTPListener/FTPPULL/node_modules/ftp/lib/connection.js:273:20)',
     '    at Socket.emit (events.js:107:17)',
     '    at readableAddChunk (_stream_readable.js:163:16)' ]
```

**Comment by atasciuc** [comment]
So the problem appears to be if you try to re-use the connection. For example if you open the connection -> list the files then close the connection than open the connection again ( note: the work is performed on the same object all the time) and try to list the files again.
