### ISSUE TITLE
Unable to parse PASV server response

### ISSUE THREAD

**Issue by aviynw** [mscdex/node-ftp#93]
I'm getting "Unable to parse PASV server response" when I try to run any command (get/put/list).  Everything is running fine when I run a number of other ftp programs like filezilla.

Here is the output in my server log which is running proftp.

"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:22 +0000] "USER userftp" 331 -
"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:22 +0000] "FEAT" - -
"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:22 +0000] "TYPE I" 200 -
"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:22 +0000] "TYPE A" 200 -
"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:22 +0000] "TYPE A" 200 -
"IP ADDRESS" UNKNOWN - [15/Aug/2014:19:03:23 +0000] "PASV" 530 -

And here is my output for a successful connection from filezilla

"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:12 +0000] "PASS (hidden)" 230 -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "SYST" 215 -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "FEAT" - -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "PWD" 257 -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "TYPE I" 200 -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "PASV" 227 -
"IP ADDRESS" UNKNOWN userftp [15/Aug/2014:19:03:13 +0000] "MLSD" 226 221

I'm not sure the best way to debug.  Any help would be appreciated.  Looking at the server logs it looks like it might not not be sending the password?  There is no log for a "PWD" command like there is for the filezilla request.

Thanks.

**Comment by phishy** [comment]
This client library also throws this same error while using npm ftpd as a server. Both these things would be great for testing and should totally work together. https://www.npmjs.com/package/ftpd

**Comment by samkohli** [comment]
Is this fixed? I am also getting this error....intermittently

**Comment by mscdex** [comment]
@samkohli Can you post your debug output?

**Comment by mscdex** [comment]
@phishy If you have have debug output, can you post it too?

**Comment by Kadasiddha** [comment]
Hi, I am also facing the same issue in the 'c.list' and 'c.put' methods. My code is given below:

        c.on('ready', function() {
            c.list('/monthly_stmt/',0,function(errftp,dataftp){
                                            
                      if (errftp){
                              console.log(errftp);
                      }
                      else{
                             console.log(dataftp);
                       }

               });
         });
         c.connect(config);

Error: Unable to parse PASV server response
    at Object.reentry [as cb] (/Users/kadasiddha/Documents/Documents/Backend/node_modules/ftp/lib/connection.js:857:19)
    at Parser.<anonymous> (/Users/kadasiddha/Documents/Documents/Backend/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/Users/kadasiddha/Documents/Documents/Backend/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Parser.Writable.write (_stream_writable.js:247:11)
    at Socket.ondata (/Users/kadasiddha/Documents/Documents/Backend/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:96:13)

**Comment by wenlong-xyz** [comment]
I met this issue today.
For my case, its due to network ip.
```
Server log: 

39.106.123.123:41678-[testuser] Rejected data connection from foreign address 172.17.135.124:39686.

Client log: 

[Error] ftp disconnet!
[Error][uploadFtpAsync]   Error: Unable to parse PASV server response
    at Object.reentry [as cb] (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:857:19)
    at Parser.<anonymous> (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:126:13)
    at Parser.emit (events.js:214:7)
    at Parser._write (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:116:13)
Error: Unable to parse PASV server response
    at Object.reentry [as cb] (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:857:19)
    at Parser.<anonymous> (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:126:13)
    at Parser.emit (events.js:214:7)
    at Parser._write (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (/usr/share/nginx/html/data-center-admin/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:116:13)

```

39.106.123.123 is the public internet ip of ftp client machine and 172.17.135.124 is the local area network ip of ftp client machine. Ftp client and server are in the same local area network. I create the connetion using FTP server's public internet ip. And then transport data, received the above error, seems it's due to data trasporting using local area network ip. Connection ip is different to data transport ip. So rejected by server.

Fixed by changing connection ip to local area network ip.

**Comment by TomlDev** [comment]
I had the same issue when setting the host to `localhost`
Fixed by using `127.0.0.1`

**Comment by ashuvax** [comment]
It's like that with me too sometimes, is there a solution to this?

**Comment by tsofist** [comment]
> It's like that with me too sometimes, is there a solution to this?

In my case, this problem occurred due to an attempt to transfer files in parallel (accidentally).
Just don't do that :)

**Comment by ashuvax** [comment]
Indeed it happened to me because I transferred files at the same time
There is no possibility to transfer files at the same time?

**Comment by tsofist** [comment]
> Indeed it happened to me because I transferred files at the same time
> There is no possibility to transfer files at the same time?

Nope. But you can create multiple clients and share files for sending

**Comment by ashuvax** [comment]
> > Indeed it happened to me because I transferred files at the same time
> > There is no possibility to transfer files at the same time?
> 
> Nope. But you can create multiple clients and share files for sending

Can you write an example please?

**Comment by tsofist** [comment]
> Can you write an example please?

It all depends on your task. Such logic can be very complex depending on the capabilities of the server: someone allows many connections from one client, and someone restricts it. To implement complex logic, I would recommend switching to lftp - it takes on a lot of complexity.

https://lftp.yar.ru/features.html

**Comment by eemailkrishna** [comment]
![image](https://github.com/user-attachments/assets/fdb9a22a-c0fb-4492-afbf-86e4c44ef91a)

if you are using internet with jio sim , then you will have to change your sim APN setting ,replace with  www.google.com or JioNet
